### ISSUE TITLE
Sort organizations into folders

### ISSUE THREAD

**Issue by Zettt** [seattlerb/omnifocus#15]
It would be great to have the ability to sort different organizations into folders. I'm working with about 4 to 5 clients and it's hard to keep track which OmniFocus project belongs to which organization since they're sorted alphabetically.

**Comment by zenspider** [comment]
I'm not sure what you're referring to. Sort where?

**Comment by zenspider** [comment]
I think `sort` is a misnomer here, as any ordering is manual and handled in omnifocus.

You just want folders, yes?

**Comment by zenspider** [comment]
No response...

**Comment by zenspider** [comment]
No response from OP for 4 weeks. Closing.
